### ISSUE TITLE
I cant convert to TMx

### ISSUE THREAD

**Issue by cutiyar** [rmraya/TMXEditor#1]
I exported a .csv file and wanted to convert it to .tmx, but when trying to set language it shows that no columns found, i did opened the .csv file and everything is good and words there.

**Comment by rmraya** [comment]
Already fixed on release 2.1.2

**Comment by rmraya** [comment]
additional changes are needed

**Comment by cutiyar** [comment]
I have 2.1.2 already and not working.

**Comment by rmraya** [comment]
Check 2.1.3 and send a test case to tech@maxprograms.com if it is not fixed.
