### ISSUE TITLE
Special could not be detected as csv

### ISSUE THREAD

**Issue by cutiyar** [rmraya/TMXEditor#2]
Hey 
now i have specail files that app can not detect its columns, how i can fix it? all the files cannot be readed by TMXeditor.
[ku_ui_strings_glossary_july_2018_x86_x64_12866510.zip](https://github.com/rmraya/TMXEditor/files/4744386/ku_ui_strings_glossary_july_2018_x86_x64_12866510.zip)

Best Regards.

**Comment by rmraya** [comment]
I am able to convert those file to TMX 

You can ask for help at https://groups.io/g/maxprograms/
