### ISSUE TITLE
Modernized the app

### ISSUE THREAD

**Issue by vrudikov** [rmraya/TMXEditor#3]
Hi, @rmraya. Appreciate your work and the tech you made

I decided to modernize the app and did some work on it:
- updated it to Gradle builds and Java Native Images. Added Gradle wrapper to avoid Ant downloading from official site
- dropped support for Ant
- fixed some bootstrap issues in typescript app
- set Java 9 as minimal required

Created it in my project/branch, so you can check it first
https://github.com/vrudikov/TMXEditor/tree/feature/gradle-build

Leave your feedback please

**Comment by rmraya** [comment]
Hello Valentin

What you did violates license terms. You cannot redistribute code from Maxprograms without permission.

Your repository contains code from Maxprograms, please make your fork private or delete it from GitHub.

Thanks,
Rodolfo

**Comment by vrudikov** [comment]
This is the copy from your LICENSE file

> Permission is hereby granted, free of charge, to any person obtaining a copy of 
> this software and associated documentation files (the "Software"), to compile, 
> modify and use the Software in its executable form without restrictions.
> 
> Redistribution of this Software or parts of it in any form (source code or 
> executable binaries) requires prior written permission from Maxprograms.

@rmraya but I don't want to redistribute it. I improved it for you and other OSS users, because code is shared here as OSS and you wrote that I can [compile, modify, use]

I compiled, modified and used. Is I'm wrong?

**Comment by rmraya** [comment]
You can compile, modify and use, but you can't redistribute the code in any form. 

By uploading Maxprograms code to a public server you are redistributing source code. That's something you are not allowed.

You can keep your changes privately or submit a pull request if you want to share them, but you must remove your fork from GitHub.

Please make sure that code from TMXEditor can't be found in your GitHub profile, as it was published without prior written permission.

Thanks,
Rodolfo

**Comment by vrudikov** [comment]
@rmraya Thanks, now it's SUPER CLEAN. Moving to private... and gonna add PR

**Comment by rmraya** [comment]
You can compile, modify and use, but you can't redistribute the code in any form. 

By uploading Maxprograms code to a public server you are redistributing source code. That's something you are not allowed.

You can keep your changes privately or submit a pull request if you want to share them, but you must remove your fork from GitHub.

Please make sure that TMXEditor can't be found in your GitHub profile, as it wos published without prior written permission.

**Comment by vrudikov** [comment]
@rmraya already removed

**Comment by rmraya** [comment]
Thanks!
