### ISSUE TITLE
Not open source — incorrect use of the term

### ISSUE THREAD

**Issue by andrewshadura** [rmraya/TMXEditor#4]
The license states:

> Redistribution of this Software or parts of it in any form (source code or executable binaries) requires prior written permission from Maxprograms.

Unfortunately, this violates the point 1 of the open source definition:

> 1. Free Redistribution
> The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.

The license doesn’t allow further distribution of the source code:

> 2. Source Code
> The program must include source code, and must allow distribution in source code as well as compiled form. Where some form of a product is not distributed with source code, there must be a well-publicized means of obtaining the source code for no more than a reasonable reproduction cost, preferably downloading via the Internet without charge. The source code must be the preferred form in which a programmer would modify the program. Deliberately obfuscated source code is not allowed. Intermediate forms such as the output of a preprocessor or translator are not allowed.

The license also doesn’t allow derived works:

> 3. Derived Works
> The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software.

While the license doesn’t explicitly say so, the README file says “Source code of TMXEditor is free for personal use”, which may or may not be discrimination against persons or groups or fields of endeavour, violating points 5 or 6 of the definition, or both.

To avoid confusion, please refrain from using the term *open source* to refer to your software or its license until the license changes to a compliant one, if ever. The term you may want to use instead is [source available](https://en.wikipedia.org/wiki/Source-available_software).

Thanks.

**Comment by rmraya** [comment]
Thanks for the comment, Andrew.

The definition of open source that I considered is the one published at [https://opensource.com/resources/what-open-source](https://opensource.com/resources/what-open-source), which states:

> Open source software is software with source code that anyone can inspect, modify, and enhance.

TMXEditor license allows all actions described in the definition above.

Anyone can inspect, modify, and enhance TMXEditor's code. A limitation on distribution rights does not restrict all other rights.

Regards,
Rodolfo M. Raya

**Comment by andrewshadura** [comment]
I don’t think you understood the issue I reported correctly.

The full open source definitions is here: https://opensource.org/osd. Even the page you linked to says:

> Open source software is different. Its authors make its source code available to others who would like to view that code, copy it, learn from it, alter it, or share it. LibreOffice and the GNU Image Manipulation Program are examples of open source software.

Your license doesn’t allow sharing; instead, it explicitly forbids it.

**Comment by andrewshadura** [comment]
Allowing sharing is the principal point of open source, without being able to share your changes, it loses the meaning.

**Comment by rmraya** [comment]
We are looking at different concepts of open source. Your view is wider and goes beyond source code availability, that's fine for me.

My view is simply different. For me, the principal point of open source is the possibility to inspect the code and make changes. The ability to share is a nice to have but not a mandatory requirement.

Regards,
Rodolfo M. Raya

**Comment by andrewshadura** [comment]
There are no different concepts of open source, it’s only one. Open source is defined by the open source definition, the term has no other meaning and didn’t exist before the OSI and Christine Peterson invented it:

https://opensource.com/article/18/2/coining-term-open-source-software

To be called open source, your license *has* to fulfil the definition.

Open source is also a trade mark, so you’re currently using the term in violation of it.

**Comment by rmraya** [comment]
Removed mention of open source

**Comment by andrewshadura** [comment]
Thanks!
