### ISSUE TITLE
BUILD FAILED - TMXEditor\build.xml:46: Problem: failed to create task or type link

### ISSUE THREAD

**Issue by ahbic** [rmraya/TMXEditor#5]
Hi, thanks for making TMXEditor, making it open source and providing build instructions!

I can't build. Perhaps I'm just using a too old version of something? Seems to match the readme instructions though.

```
PS D:\TMXEditor> node --version
v16.6.1
PS D:\TMXEditor> ant -version
Apache Ant(TM) version 1.9.16 compiled on July 10 2021
PS D:\TMXEditor> java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
PS D:\TMXEditor> ant
Buildfile: D:\TMXEditor\build.xml

distclean:

clean:
   [delete] Deleting directory D:\TMXEditor\out

init:
    [mkdir] Created dir: D:\TMXEditor\out
     [copy] Copying 6 files to D:\TMXEditor\out

compile:
   [delete] Deleting: D:\TMXEditor\jars\tmxserver.jar
    [javac] Compiling 26 source files to D:\TMXEditor\out
      [jar] Building jar: D:\TMXEditor\jars\tmxserver.jar

link:

BUILD FAILED
D:\TMXEditor\build.xml:46: Problem: failed to create task or type link
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.


Total time: 1 second
```

Lines 46-48 of build.xml are:
```
        <link destDir="dist" modulepath="jars:${java.home}/jmods">
            <module name="tmxserver"/>
        </link>
```

**Comment by rmraya** [comment]
Works for me.

Check the support options in README.md file

**Comment by ahbic** [comment]
Thanks for the feedback.

If anybody would like to share their what version they use to make it work, I'd appreciate it.

**Comment by vn342** [comment]
This issue has been closed but was not solved. I am experiencing the same problem as ahbic.

BUILD FAILED
D:\TMXEditor\build.xml:46: Problem: failed to create task or type link
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

I am building in Windows 11.
I appreciate any help anyone may have. Thanks!
